version: '3'
services:
  mysql:
    image: mysql:8.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flow
      - MYSQL_USER=flow
      - MYSQL_PASSWORD=flow
    ports:
      - 3306:3306