# project information
site_name: Railway FBP
site_author: Mathieu Ledru
site_url: https://darkwood-fr.github.io/railway-fbp
site_description: >-
  Railway Flow Based Programming concept and implementation.

# repository
repo_name: darkwood-fr/railway-fbp
repo_url: https://github.com/darkwood-fr/railway-fbp
edit_uri: tree/1.x/docs

# copyright
copyright: Copyright &copy; 2021 Mathieu Ledru @matyo91

# configuration
docs_dir: docs
theme:
  name: material
  custom_dir: docs/theme
  font:
    text: Roboto
  #analytics:
  #  gtag: G-G0N1ZYBL0F
  palette:
    # light mode
    - primary: light
      toggle:
        icon: mode/light
        name: Switch to dark mode
    # sepia mode
    - primary: sepia
      toggle:
        icon: mode/sepia
        name: Switch to light mode
    # dark mode
    - primary: dark
      toggle:
        icon: mode/dark
        name: Switch to sepia mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    logo: logo
  logo: images/logo.png
  favicon: images/favicon.ico

# customization
extra_css:
  - css/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/darkwood-fr/railway-fbp
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/darkwood_fr
    #- icon: fontawesome/brands/linkedin
    #  link: https://www.linkedin.com/company/darkwood-fr
    #- icon: fontawesome/brands/facebook-f
    #  link: https://www.facebook.com/darkwood.fr

# page tree
nav:
  - Getting started:
      - Introduction: index.md
      - Drivers: getting-started/drivers.md
      - Ip Strategy: getting-started/ip-strategy.md
      - Ressources: getting-started/ressources.md
      - Release Notes: getting-started/changelog.md
      - License: getting-started/license.md
