name: Continuous Integration

on:
  push:
    branches:
      - 1.x
  pull_request:

jobs:
  cs-fix:
    name: Check and fix coding styles using PHP CS Fixer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: xsl, openswoole
          tools: composer
          coverage: none # disable XDebug for tests

      - name: Install dependencies
        run: composer install -d tools/php-cs-fixer

      - name: PHP-CS-Fixer
        run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --config .php-cs-fixer.php  --diff --dry-run

  phpstan:
    name: Execute PHPStan analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: xsl, openswoole
          tools: composer
          coverage: none # disable XDebug for tests

      - name: 'Install dependencies'
        run: |
          composer install -d tools/phpstan
          composer install

      - name: PHPStan
        run: tools/phpstan/vendor/bin/phpstan --configuration=phpstan.neon

  phpunit:
    name: Launch PHPUnit test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2' ]
    steps:
      - name: Init repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: xsl, openswoole
          tools: composer
          coverage: none # disable XDebug for tests

      - name: Install dependencies
        run: composer install

      - name: PHPUnit
        run: vendor/bin/phpunit