name: Code Quality

on:
  push:
    branches:
      - 1.x
  pull_request:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.0' ]
        package: [ 'php', 'symfony' ]

    steps:
      - name: 'Init repository'
        uses: actions/checkout@v2

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: xsl, swoole
          tools: composer
          coverage: none # disable XDebug for tests

      - name: 'Install dependencies'
        run: composer  --working-dir=packages/${{ matrix.package }} install

      - name: 'PHPStan'
        run: composer  --working-dir=packages/${{ matrix.package }} phpstan

      - name: 'PHP-CS-Fixer'
        run: composer  --working-dir=packages/${{ matrix.package }} cs-fix

      #- name: 'Psalm'
      #  run: composer  --working-dir=packages/${{ matrix.package }} psalm

      #- name: 'PHPQA'
      #  run: composer  --working-dir=packages/${{ matrix.package }} phpqa

      - name: 'Test suite'
        run: composer  --working-dir=packages/${{ matrix.package }} test