name: Code Quality

on:
  push:
    branches:
      - 1.x
  pull_request:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.2' ]

    steps:
      - name: 'Init repository'
        uses: actions/checkout@v3

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: xsl, swoole
          tools: composer
          coverage: none # disable XDebug for tests

      - name: 'Install dependencies'
        run: composer install

      - name: 'PHPStan'
        run: composer phpstan

      - name: 'PHP-CS-Fixer'
        run: composer cs-fix

      #- name: 'Psalm'
      #  run: composer psalm

      #- name: 'PHPQA'
      #  run: composer phpqa

      - name: 'Test suite'
        run: composer test