name: Docs Deploy

on:
  push:
    branches:
      - 1.x

jobs:
  docs-deploy:
    name: Docs Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
      - name: Deploy
        run: |
          mkdocs gh-deploy -c --force
          mkdocs --version